### ISSUE TITLE
In 2D images, layerCount = 0 and faceCount = 1

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/KTX-Specification#110]
When implementing support for a KTX writer, I found out that the spec says that layerCount should be 0 and faceCount should be 1.

This seems oddly inconsistent. It would make sense to me if both variables had to be 0 for 2D images (making sure that 2D images are treated specially and correctly), or 1 (treating 2D images as single-layer single-face image, whereas a single cubemap is single-layer 6-face, and a texture array is N-layer 1-face).

Is this intentional?

**Comment by MarkCallow** [comment]
It is intentional. Normally both of these should be 1 for a 2D texture but `layerCount == 0` is used to indicate a non-array texture while `layerCount ==1` indicates an array texture. The distinction is important for OpenGL were different targets must be used. I do not know how much the distinction is used in practice especially as it is not needed with Vulkan. I don't know about DX12 or Metal.

KTX 1 is the same in this regard so a survey of KTX 1 files might provide some data.

**Comment by zeux** [comment]
Ah - right - I missed that there's no explicit "type" field, so type is inferred. That makes sense, thanks!
