### ISSUE TITLE
How to specify handling of vkFormat == VK_UNKNOWN_FORMAT case

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Specification#12]
There are cases when we can have a valid DFD together with `vkFormat == VK_UNKNOWN_FORMAT`.  Removing the GL format related fields as proposed in issue #8 will likely increase the chances of this happening. Examples might be older GL formats such the formats in `OES_compressed_paletted_texture`.

Several questions:

1. Do we try to specify anything about handling this case or leave it entirely up to the applications how to handle a valid DFD and `vkFormat == VK_UNKNOWN_FORMAT`?

2. Should a file be considered valid if the DFD is valid and there is a matching VK_FORMAT yet `vkFormat == VK_UNKNOWN_FORMAT`? Note that there is not a 1:1 mapping of DFD to VK_FORMAT. So if this case is allowed the format used by a loader will not be deterministic.

**Comment by jherico** [comment]
> Should a file be considered valid if the DFD is valid and there is a matching VK_FORMAT yet vkFormat == VK_UNKNOWN_FORMAT? 

I'd say no, because ideally a valid file should have exactly one possible representation of it's data, or at the very least, the minimum possible number of representations.

**Comment by MarkCallow** [comment]
@jherico What does "representation" mean here?

**Comment by fluppeteer** [comment]
Oh - sorry, now I understand some confusion in a private email about VK_UNKNOWN_FORMAT. :-)

I think KTX2 should explicitly state the list of formats which it can encode, otherwise it's impossible for third-party implementations to guarantee that everything is supported. Vulkan and GL can both support the addition of formats by extensions, and don't mandate that all formats are supported on a given platform, so the enums aren't canonical.

In the case of a format that has no equivalent Vulkan format (such as the paletted case), I'd just mandate what that format has to look like in DFD terms - with a fuzzy match for the fields (such as colour primaries) which can have multiple values without affecting the mapping.

**Comment by MarkCallow** [comment]
> I think KTX2 should explicitly state the list of formats which it can encode, otherwise it's impossible for third-party implementations to guarantee that everything is supported. Vulkan and GL can both support the addition of formats by extensions, and don't mandate that all formats are supported on a given platform, so the enums aren't canonical.

The problem is those 3rd party extensions. I don't see any reason for KTX to refuse to encode those formats, which would happen if we put in an explicit list of formats. It's up to the reading system whether its GL or Vulkan can accept those formats. Also the reader could have its own handling for them or maybe isn't trying to use them with GL or Vulkan.

Note that this comment does not apply to use of KTX2 in glTF. For that use we will almost certainly have an explicit and probably short list. That is a matter for the glTF spec not the KTX spec.

> In the case of a format that has no equivalent Vulkan format (such as the paletted case), I'd just mandate what that format has to look like in DFD terms - with a fuzzy match for the fields (such as colour primaries) which can have multiple values without affecting the mapping.

Please provide an example of what such a mandate would look like.

**Comment by fluppeteer** [comment]
Should there not be an explicit list of formats that unexpanded KTX2 can encode, which can be supplemented by means of extensions? Then a decoder can tell whether it can handle a given file by checking for extension compatibility. I suppose the onus is then on the writer to ensure that it only uses the minimum set of extensions for whatever it's decided to write (so you don't need the "PVRTC" extension if you don't actually write a PVRTC image, for example). I'm wary that accepting an arbitrary data format descriptor, at least in code that's not explicitly designed to perform conversions, is going to involve more work than cross-referencing an enum list. If you're programmatically decoding the content, that's different, but mapping to a graphics API format and relying on the hardware to sort out the decode doesn't need too much understanding of the content.

> Please provide an example of what such a mandate would look like.

Let's say R8_UNORM (as in "it's a byte that encodes 0..1 in an unsigned integer) could be matched by:

- a 1x1x1x1 texel block
- color model doesn't really matter, though we could mandate RGBSDA
- transfer function linear or undefined (depending on what you plan to do with it - basically not R8_SRGB)
- color primaries don't matter
- 1 plane containing 1 byte
- 1 sample
- data in bits 0..7
- channel doesn't matter (because you could reasonably write green and read R8 if you wanted to...)
- sample location 0,0,0,0 (not that anything else makes sense)
- sample lower 0
- sample upper 255 (because 255 means "1.0" for UNORM)

It should be A Small Matter Of Programming (but I haven't done it yet) to provide a function that matches some sections of a data format descriptor while ignoring others, but from the spec's perspective, you could either explicitly show the fields that matter (as in the examples at the end of the data format spec) or show the bit pattern, with "x" for "don't care" - or both.

**Comment by jherico** [comment]
By representation I mean a sequence of bytes on disk or in memory, i.e. a file, possibly memory mapped.

**Comment by fluppeteer** [comment]
@jherico I agree that this (where "this" means both having a defined endianness for the descriptive metadata and having a defined endianness for the actual texel values) simplifies loading software, even if it means that software always has some work to do on some architectures. Swizzling data (or in some cases just providing a mapping) is not a slow operation compared with accessing storage, or even decompression, and is well-suited to SIMD instruction acceleration.

I do think a canonical representation of the terms that should be defined helps - I've tried to do this in the data format spec, but another ambiguity (whether consecutive bits of the same channel should be described in strictly consecutive samples) came up during discussion; I'll resolve this in an update.

There is an issue here that whether two formats are "the same" depends what you're doing with them. If you care about colour space, you need these fields to match; if you don't, you can ignore them. I intend to clarify a bit which operations need to care about certain fields, and that includes the way extensions work. Since Vulkan has no concept of colour spaces (at least for RGB by default), something performing a mapping in KTX2 probably should be ignoring these fields of the DFD - but it's up to the application to decide whether this information is, in fact, important.

**Comment by jherico** [comment]
> If you care about colour space, you need these fields to match; if you don't, you can ignore them

I feel like at this point, color space is like UTF-8.  If you're not taking it into account, you're _doing it wrong_.    

> Since Vulkan has no concept of colour spaces

I don't follow what you mean by that.  Every 8 bit unorm format (like VK_FORMAT_R8G8B8A8_UNORM) has a corresponding SRGB version (i.e. `VK_FORMAT_R8G8B8A8_SRGB`).  The SurfaceKHR extension also explicitly has a list of like a dozen different color spaces for the display surface.

**Comment by fluppeteer** [comment]
> I feel like at this point, color space is like UTF-8. If you're not taking it into account, you're doing it wrong.

Depends what you mean by "it". You can do a lot of valid byte operations on a sequence of chars without choosing to interpret them as having UTF-8 encoding.

> I don't follow what you mean by that. Every 8 bit unorm format (like VK_FORMAT_R8G8B8A8_UNORM) has a corresponding SRGB version (i.e. VK_FORMAT_R8G8B8A8_SRGB).

It does. Which means that the sRGB EOTF or inverse EOTF should be applied to the R, G and B channels when accessing the format, compared with a linear transformation. It means precisely nothing about the colour primaries or white point, or indeed colour model. That's even more the case for the formats with linear conversions to and from UNORM. The format may be labelled RGBA, but all this tells you is which byte arrives in which named component of the colour quad inside a shader. If you elect to interpret this data as CMYK, or byte swapped BGRA, or a series of components of a vector, that's entirely up to your program.

> The SurfaceKHR extension also explicitly has a list of like a dozen different color spaces for the display surface.

Indeed. These define how the content of a display surface is going to be interpreted by display hardware. You can choose to transform the values your shader has been working with into that interpretation, in order to have a known final representation for display. But that's only for the display system; nothing defines the interpretation of channels in a texture other than the application author.

The intent is that the data format spec can say "this image is actually meant to be interpreted in the following way" - and KTX can do the same. This allows portable software to do the right thing without needing to have an interpretation of the texture "format" hard-wired. Even then, a colour space in the texture format defines only the source - the colour space your shader chooses to work in is entirely up to you, and you need both for the transform.

Or you may choose that you don't care what the colour space is. If the transfer function is linear and the model is additive, you can perform filter operations (including resizing) on a texture while not remotely caring what the colour primaries are, for example. You may also be able to make some assumptions about the input, based on where you got it from. But Vulkan doesn't know any of this - for its internal formats, it just gives you numbers, and the rest is up to you.

(The Vulkan spec actually uses the full colour names more than I thought it did. Probably more than it should...)

**Comment by jherico** [comment]
> The intent is that the data format spec can say "this image is actually meant to be interpreted in the following way" - and KTX can do the same. 

That sounds like a great job for an extension.

**Comment by MarkCallow** [comment]
> That sounds like a great job for an extension.

An extension to KTX? Providing this info is one of the main reasons for including a DFD in KTX2. An extension is therefore not necessary.

**Comment by MarkCallow** [comment]
>  It means precisely nothing about the colour primaries or white point, or indeed colour model.

Yes but transforms from the known color primaries of an image to, e,g. the display's primaries can be applied as the image is loaded or, with a 4x4 transform as it is sampled, by a shader. So it is still useful to provide the information.

**Comment by MarkCallow** [comment]
We have 2 formats from OpenGL that we want KTX2 to support that do not, yet, have Vulkan equivalents: the ASTC HDR and ASTC 3D formats. There is also no equivalent for the OpenGL 8_8_8_8_INT packed format. Not sure if we need to support that.

**Comment by lexaknyazev** [comment]
I still expect us to get Vulkan enums for missing ASTC formats even if existing Vulkan drivers do not support them.

Just for the record, it's OpenGL packed _type_ called `UNSIGNED_INT_8_8_8_8` (with RGBA and BGRA _formats_) that doesn't have Vulkan equivalent. Given that it's desktop-only, the same functionality could be achieved by swizzling existing formats.

**Comment by fluppeteer** [comment]
I'm not sure whether the 3D ASTC textures cause any complication to the API; I'll chase that one, because a texture format not confined to a single plane might break things, and I don't recall whether there's the concept of a block size in the third dimension. (I'm not saying it's not done right, just that I doubt anyone's looked very closely.)

I could be wrong about this (GL textures aren't my strong point), but I believe UNSIGNED_INT_8_8_8_8 will have a different idea of the location of the alpha channel from UNSIGNED_INT_8_8_8_8_REV, and that the swizzle happens after the texture has been filtered. Since the alpha channel is linear but the others may have an sRGB transfer function applied to them which is reversed prior to any filtering operations, it's not necessarily the case that you can exchange them with the swizzle. One reason for considering it relates to endianness, but since you can't swizzle your way out of any other format in the wrong endianness anyway, it's a very restrictive work-around.

**Comment by fluppeteer** [comment]
We seem to have come back to this from a long time ago, so I may be misrepresenting myself, but...

> > It means precisely nothing about the colour primaries or white point, or indeed colour model.

> Yes but transforms from the known color primaries of an image to, e,g. the display's primaries can be applied as the image is loaded or, with a 4x4 transform as it is sampled, by a shader. So it is still useful to provide the information.

I think I was just talking about whether the "sRGB" Vulkan formats had an inherent colour space associated with them (and whether anything else does). I'm just channelling Graham Sellers, who was very emphatic to me that the channels should mean just what the user chooses them to mean - neither more nor less. Agreed that once you've given something to the presentation engine, something needs to know what interpretation is being applied; KTX has the same problem in reverse, that user code needs to know what the creator of the texture is thinking. Internal calculations will be in some colour space as well, but only the user knows what that may be, and SRGB format enums don't add any constraints.

**Comment by lexaknyazev** [comment]
re ASTC
There's a slightly related issue in Vulkan repo: https://github.com/KhronosGroup/Vulkan-Docs/issues/926

---

Here're mappings for GL's packed 8_8_8_8 types/formats to `vkFormat` (assuming little-endian encoding).

**_Italic_ enums do not exist.**

|  | UNSIGNED_INT_8_8_8_8 | UNSIGNED_INT_8_8_8_8_REV |
|--------------|--------------------------|--------------------------|
| RGBA | _VK_FORMAT_A8B8G8R8_UNORM_ | VK_FORMAT_R8G8B8A8_UNORM |
| BGRA | _VK_FORMAT_A8R8G8B8_UNORM_ | VK_FORMAT_B8G8R8A8_UNORM |
| RGBA_INTEGER | _VK_FORMAT_A8B8G8R8_UINT_ | VK_FORMAT_R8G8B8A8_UINT |
| BGRA_INTEGER | _VK_FORMAT_A8R8G8B8_UINT_ | VK_FORMAT_B8G8R8A8_UINT |

AFAIU, they are not supported anywhere except desktop OpenGL, so we can safely omit them from KTX2.

---

My understanding is that "_SRGB" in `vkFormat` denotes transfer function because it's required for accurate filtering operations. Primaries don't have to be sRGB although they commonly are.

**Comment by fluppeteer** [comment]
Yup, there's hardware that applies the sRGB transfer function - it's an efficiency thing for unfiltered operations, but as you say, filtering relies on linearised content, so it has to be applied before you can sample filtered content. This is a known awkwardness for Y'CbCr content that uses the ITU transfer function instead - to filter it correctly you should really be point sampling, linearise, then do any filtering in the shader. I was only responding to Mark reviving the discussion about the need for colour space information, though!

And yes, GLES lacks these formats - my working theory of why they got omitted from Vulkan is that Vulkan is designed with a minimum spec of GLES 3.1-compatible hardware, and any optional functionality on top of that needs to be justified. Technically it would be better to say that UNSIGNED_INT_8_8_8_8_REV + RGBA is VK_FORMAT_A8B8G8R8_UNORM_PACK32 and UNSIGNED_INT_8_8_8_8_REV + RGBA_INTEGER is VK_FORMAT_A8B8G8R8_UINT_PACK32, but on a little-endian architecture they're equivalent (and there's no VK_FORMAT_A8R8G8B8_*_PACK32, so pick your inconsistency - though that one you _can_ fix with swizzles).

**Comment by fluppeteer** [comment]
Incidentally, a cursory glance suggests that Vulkan may not obviously break if 3D ASTC compressed texel blocks are used (the depthPitch calculations look plausible), so it may be a matter of demand and drivers.

**Comment by MarkCallow** [comment]
CTTF TSG telecon 5/20/19. We have 3 cases for vkFormat == VK_UNKNOWN_FORMAT:

- no Vulkan format enum but a GL format. This is handled by the GL format metadata.
- custom case with no Vk or GL enums. Data described with DFD. For example RGBE.
- custom case such as supercompressed universal format where DFD can't help either. Such case(s) will be explicitly documented.

We're in good shape regarding the first 2. Will document each specific case of the last as needed.

Closing this.
