### ISSUE TITLE
mipMap=0 should not imply autogeneration

### ISSUE THREAD

**Issue by dewilkinson** [KhronosGroup/KTX-Specification#29]
ISVs are pointing out that this Language is making strong assumptions about runtime behaviour. The choice to auto generate levels is the responsibility of the app at runtime , should not be part of the file format

**Comment by MarkCallow** [comment]
If apps don't want auto generation they can avoid specifying `numberOfMipmapLevels = 0`. Auto-generation has been in KTX since the beginning and this is the first time it has been suggested it should not be in the file format. The discussion that led to its inclusion was a long time ago so I'm afraid I don't recall the reasons.

**Comment by lexaknyazev** [comment]
There's a more general notion within Khronos that file formats should just describe data without defining runtime behavior. I think in this particular case, the spec can be a bit more subtle like:
- `numberOfMipmapLevels = 1` means that a file contains only the first level and the texture isn't meant to have other levels. E.g. this could be a LUT rather than a natural image.
- `numberOfMipmapLevels = 0` means that a file contains only the first level and engines should generate other levels if needed. In other words, it describes _intent_ rather than strict runtime behavior.

**Comment by dewilkinson** [comment]
Reviewed on 12/21 call

It was agreed that the spec rework suggested by Alexey above would be the correct approach. Ie

numberOfMipLevels=[0,1] 

Defines the actual number of Miplevels present (1, or >1) and leaves the app to decide whether to autogenerate, and not the decoder/reader

**Comment by MarkCallow** [comment]
Fixed by PR #46.
