### ISSUE TITLE
ISV KTX usability feedback

### ISSUE THREAD

**Issue by dewilkinson** [KhronosGroup/KTX-Specification#33]
ISV feedback (multiple sources). Repeat of request for indexability, use of JSON

“Overall, this seems like a format I wouldn’t like to support, because it’s more complicated than necessary and at the same time not as flexible as it should be. Something similar to a binary JSON representation would have been much easier for everyone, but at least it could be made into a format with a “index table” at the beginning to make it seek-friendly.”

**Comment by MarkCallow** [comment]
I am not very familiar with JSON especially not with having binary data in them. KTX will also be used on native so are there implementations of a JSON loader in C or C++.

What kind of flexibility is the person quoted seeking? Why would JSON provide that?

Re. an index table, see my comment in issue #32.

Re. "more complicated than necessary" textures in their full glory are complicated.

**Comment by jherico** [comment]
>  What would a JSON version look like?

Probably like GLTF, but for texels instead of vertices.  I get the appeal.  _I_ enjoy writing low level code that will memory map a file and populate a header structure just by casting a pointer to `ktx::Header*`, but that's a very C/C++-centric way of doing things.  Most higher level languages have functionality built in that will take JSON and convert it directly to a language native hierarchical structure, like Python converting JSON to a dictionary.  That suddenly makes manipulating metadata (in the sense of ALL information about the image, not just the KTX 1 metadata sense) trivial compared to the strict byte-wise layout.  

Another thing that's probably appealing about the GLTF model is the flexibility of bundling stuff.  You have a metadata file which is small enough that no one minds downloading it in its entirety, and then N blocks of binary data.  All of it can be bundled together in a GLB file, or it can be set up as distinct files.   

This in turn makes it easy to do inline transformation of an image between the hosted version (lots of formats, lots of mips) and a local version (a subset of formats and mip sizes suited to the client architecture).

**Comment by lexaknyazev** [comment]
> Most higher level languages have functionality built in that will take JSON and convert it directly to a language native hierarchical structure, like Python converting JSON to a dictionary.

Even higher level languages produce arrays and dictionaries out of JSON rather than native structures because JSON is too flexible to be directly mapped onto regular OOP classes / instances. To achieve "native" look and feel, one would need to have a domain-specific serialization/deserialization layer (that could in many cases be auto-generated from JSON-Schema definitions).

I can see some benefits in detaching KTX2 header into its own file to reduce the number of seeks/reads especially over the network.

By "binary JSON", OP probably meant something like [UBJSON](http://ubjson.org) - a 1:1 binary storage representation for regular text-based JSON.

**Comment by MarkCallow** [comment]
I have a strong preference for keeping everything together in a single file. Given that ranges can be read via HTTP{,S} it must be possible to fetch only the header. Separate files will cause various headaches such as when dealing with CRN's global code book.

**Comment by dewilkinson** [comment]
Consensus on 12/21 call was to keep everything together in one file, but simplify the header and data sections. 

The idea of using JSON was discussed, and it was agreed that it was an interesting idea, but implementing the required changes (including platform specific serializers/deserializers) would be out of scope for v1.0 . Rather we would prefer to keep the base format as is for now, and offer a JSON option as part of our supporting toolkit. We would include an appendix in the spec for using JSON KTX2

**Comment by MarkCallow** [comment]
It was suggested that applications could create their own JSON files containing just the header information. That is what will be described in the appendix.

**Comment by MarkCallow** [comment]
This is how I am thinking of rearranging the header:

```c
Byte[12] identifier
UInt32 vkFormat
UInt32 pixelWidth
UInt32 pixelHeight
UInt32 pixelDepth
UInt32 numberOfArrayElements
UInt32 numberOfFaces
UInt32 numberOfMipmapLevels
UInt32 supercompressionScheme
UInt64 bytesOfImages
UInt64 bytesOfUncompressedImages

// Offsets
UInt32 dfdOffset
UInt32 keyValueDataOffset
UInt64 supercompressionGlobalDataOffset
UInt64 levelOffsets[numberOfMipmapLevels] <1>

// Data Format Descriptor
UInt32 bytesOfDataFormatDescriptor <2>
for each dfDescriptorBlock that fits in bytesOfDataFormatDescriptors
    dfDescriptorBlock descriptorBlock
    blockPadding[3 - ((descriptor_block_size + 3) % 4)]
end

// Key-Value Data
UInt32 bytesOfKeyValueData
for each keyValuePair that fits in bytesOfKeyValueData
    UInt32   keyAndValueByteSize
    Byte     keyAndValue[keyAndValueByteSize]
    Byte     valuePadding[3 - ((keyAndValueByteSize + 3) % 4)]
end
Byte keyValuePadding[0|4]

// Supercompression Global Data
UInt64 bytesOfSupercompressionGlobalData
Byte supercompressionGlobalData[bytesOfSupercompressionsGlobalData]
Byte sgdPadding[7 - ((bytesOfSupercompressionGlobalData + 7) % 8)]]

// Mipmap Level Array
for each mipmap_level in numberOfMipmapLevels <1>
    Uint64 bytesOfLevelImages
    Uint64 bytesOfUncompressedLevelImages
    Byte levelImages[bytesOfLevelImages] <3>
    Byte mipPadding[0-7]
end
```

Among the changes, I moved `bytesOfImages` & `bytesOfUncompressedImages` to the top instead of having them just before the Mipmap Level Array. It looks nice and symmetric but I wonder if it is better to leave them where they were.

Please share your opinions on this new layout.

**Comment by MarkCallow** [comment]
Maybe I should have {offset, size} pairs instead of just offsets. A possible problem with that is that I need 2 sizes for the levels, compressed and uncompressed.

**Comment by MarkCallow** [comment]
How about this:

```c
Byte[12] identifier
UInt32 endianness
UInt32 glTypeSize
UInt32 vkFormat
UInt32 pixelWidth
UInt32 pixelHeight
UInt32 pixelDepth
UInt32 numberOfArrayElements
UInt32 numberOfFaces
UInt32 numberOfMipmapLevels
UInt32 supercompressionScheme
UInt64 bytesOfImages
UInt64 bytesOfUncompressedImages

// Offsets and Sizes
UInt32 dfdOffset
UInt32 bytesOfDataFormatDescriptor
UInt32 keyValueDataOffset
UInt32 bytesOfKeyValueData
UInt64 supercompressionGlobalDataOffset
UInt64 bytesOfSupercompressionGlobalData
struct {
    UInt64 offset;
    UInt64 bytesOfImages;
    UInt64 bytesOfUncompressedImages;
} levels[max(1, numberOfMipmapLevels)] <1>

// Data Format Descriptor
for each dfDescriptorBlock that fits in bytesOfDataFormatDescriptors
    dfDescriptorBlock descriptorBlock
    blockPadding[3 - ((descriptor_block_size + 3) % 4)]
end

// Key-Value Data
for each keyValuePair that fits in bytesOfKeyValueData
    UInt32   keyAndValueByteSize
    Byte     keyAndValue[keyAndValueByteSize]
    Byte     valuePadding[3 - ((keyAndValueByteSize + 3) % 4)]
end
Byte keyValuePadding[0|4]

// Supercompression Global Data
Byte supercompressionGlobalData[bytesOfSupercompressionsGlobalData]
Byte sgdPadding[7 - ((bytesOfSupercompressionGlobalData + 7) % 8)]]

// Mipmap Level Array
for each mipmap_level in numberOfMipmapLevels <1>
   Byte levelImages[bytesOfLevelImages] <3>
    Byte mipPadding[0-7]
end
```

Which do you prefer?

**Comment by MarkCallow** [comment]
Darn! The reordering comments should have been in issue #32 not here.

**Comment by dewilkinson** [comment]
I will review the options above and provide feedback ASAP. This may also benefit from a main 3D WG review cycle to gain more widespread feedback

**Comment by MarkCallow** [comment]
> I will review the options above

If you're referring to the reordered header, please review the proposed solution is in PR #53. It uses {offset,size} pairs. Add comments to the PR or to issue #32 or #39. This issue is for creating an appendix about apps creating their own JSON headers. Sorry again for my error.

**Comment by MarkCallow** [comment]
CTTF TSG telecon 5/20/19. The things requested here have been done except for the appendix describing creating a JSON header.  Instead of that the spec. will refer to the glTF KTX2 extension as an example of such a thing. We will also change the names of some header fields to match the glTF comventions. These will be tracked in issue #85.
