### ISSUE TITLE
Order of metadata keys

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/KTX-Specification#43]
Should KTX2 exporters/editors keep metadata keys sorted, so that checksum doesn't change on round-trip?

**Comment by MarkCallow** [comment]
I would prefer that if no changes have been made, an editor does not write the file. But I'm okay with required an order. Roman-alphabetical?

**Comment by MarkCallow** [comment]
What should the sort order be? One possibility is to follow [DUCET](http://www.unicode.org/reports/tr10/) (the Default Unicode Collation Element Table). Another is to sort in order of unicode code points. Any others?

Since the purpose of the ordering is not to make it easier for humans to find things, the complexity of DUCET is probably unnecessary. So I'd vote for sorting in order of the code points.

**Comment by lexaknyazev** [comment]
> I would prefer that if no changes have been made, an editor does not write the file.

A user may do "Save As" command, so an editor will have to write a file. Most likely, this will trigger KTX2 serialization rather than a file copy.

Code points are fine with me. While KTX2 supports UTF8 for keys, I think that vast majority of keys will only use Latin1 chars.

**Comment by MarkCallow** [comment]
Fixed by PR #56.
