### ISSUE TITLE
KTXorientation format should be same in KTX 1 & KTX 2

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Specification#67]
KTXorientation has to be handled by the application as only it knows what it needs to do to transform on convert the texture coordinates to display the image correctly. It will be simpler for applications, therefore, if the format of the KTXorientation metadata is the same in KTX 1 and KTX 2.  With them different the app has be aware whether it is loading a KTX 1 or a KTX 2 file. If it is using the libktx loaders, unless it is relying on KTX 2 specific metadata, there is no other reason it needs to  be aware.

**Comment by lexaknyazev** [comment]
I don't expect libktx users to receive raw metadata values for the keys from KTX namespace, since such values has spec-defined formats that should be handled by libktx.

Apps using their own KTX parsers and willing to support both versions would have more than one codepath anyway.

KTX2 version of `KTXorientation` is arguably much less error-prone and could be robustly implemented from scratch without using regular expressions or designing a custom parser. Keeping all other  improvements in mind, new apps that do not use libktx should focus on supporting only KTX2.

**Comment by MarkCallow** [comment]
I am concerned that if, e.g, libktx, returns enum values for the orientation in each dimension that we'll be expected to do the same for all the other metadata. Currently libktx builds a hash list of the keys & values and provides an easy way for applications to find keys of interest.

I agree new apps should focus only on KTX2.

The KTX 1 KTXorientation format can be reasonably robustly parsed just with sscanf.

```c
char s, t, r;
int count = sscanf (stringFromFile, "S=%c, T=%c, R=%c",  &s, &t, &r);
// The spaces after each comma cause sscanf to match 0 or more whitespace characters.
// The returned count tells you how many of S, T & R were matched.
```

**Comment by lexaknyazev** [comment]
> if, e.g, libktx, returns enum values for the orientation in each dimension that we'll be expected to do the same for all the other metadata

I'd expect libktx to provide strongly-typed interfaces for accessing all KTX-defined metadata entries:

**KTXcubemapIncomplete**
One value and convenient constants for checking present faces (this is arguably better than listing all 64 possible options). Optionally, helper functions could be provided as well.

**KTXorientation**
Struct with three enums. Non applicable values (e.g., R for 2D textures) could use 0 or a special value.

**KTXglFormat**
Struct with three fields.

Applications should use direct hash list access only for custom metadata.

**Comment by MarkCallow** [comment]
CTTF TSG telecon 5/20/19. Will leave KTX metadata as is. libktx will provide enums.
