### ISSUE TITLE
Basis information in the spec is outdated

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/KTX-Specification#98]
Specifically, the spec repeatedly refers to _Crunch CRN_ rather than _Basis_ and should be updated to reflect the more recognizable public name.  Additionally, there is a note in 3.8.1 that reads 

>  A file that specifies Crunch CRN with base formats other than ETC, ETC2 and BC[1-3] (S3TC_DXT[1-5]) must be considered invalid.

It looks like base format is a reference to a no longer extant field, unless I'm missing something.

**Comment by MarkCallow** [comment]
You are right. The spec. needs updating.

As for "base format", our original plan changed because of the tight coupling between ETC1S encoding & supercompression and inflation & transcoding in the BasisU software. `vkFormat` should now be VK_FORMAT_UNDEFINED for BasisU supercompressed files. Another part of the spec. that needs updating.

**Comment by MarkCallow** [comment]
Please review PR #103
